# fly.toml app configuration file generated for cool-fire-3272 on 2023-05-19T08:53:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-fire-3272"
primary_region = "arn"

[env]
   PORT = "3001"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

